server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/BASICIT?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: ajdcjddl10!
    driver-class-name: com.mysql.cj.jdbc.Driver

  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp